#safe: false
#highlighter:  rouge
#excerpt_separator: "\n\n\n"
#paginate: 5



#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "Tom的个人博客"
email: flyokzt@qq.com
description: "Tomgg个人博客"
keywords: "Tomgg"

# 用户信息设置
# weibo_username: tomgg
# github_username: tomgg

# Markdown设置
#markdown:
#  input:  GFM
#   use_coderay: true
  # coderay:
    # coderay_line_numbers:  nil



# 地址设置
baseurl: ""
url: "https://tomgg.github.io"


# 分页设置
paginate: 5
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
#duoshuo_comments: true
#duoshuo_shortname: tomgg

# 百度统计设置
# baidu_analysis:
