#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
name: "Tomgg's blogs"
title: "Tomgg's blogs"
email: flyokzt@qq.com
authors:  tomgg
description: "个人博客写一些计算机技术相关的东东！"
keywords: "IT,软件,编程,Java,web"

# 用户信息设置
weibo_username: tomgg
github_username: tomgg

# Markdown设置
#markdown:
#  input:  GFM
#   use_coderay: true
  # coderay:
    # coderay_line_numbers:  nil

highlighter: pygments
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - no_intra_emphasis
#     - autolink
#     - tables
#     - with_toc_data
kramdown:
  input:            GFM
  auto_id_prefix:   'id-'
  auto_ids:         true


# 地址设置
baseurl: ""
url: "https://tomgg.github.io"


# 分页设置
paginate: 5
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_comments: true
duoshuo_shortname: tomgg

comments_url: comment.html

# 百度统计设置
# baidu_analysis:
